
#pragma once

namespace pandemic{
    enum City{
        Algiers,
        Madrid,
        Paris,
        Atlanta,
        Chicago,
        Miami,
        Washington,
        Chennai,
        Beijing,
        Seoul,
        MexicoCity,
        Lima,
        SaoPaulo,
        BuenosAires,
        Bogota,
        Cairo,
        Istanbul,
        Baghdad,
        Riyadh,
        Bangkok,
        SanFrancisco,
        LosAngeles,
        Montreal,
        Delhi,
        Tehran,
        Karachi,
        Mumbai,
        Kolkata,
        London,
        Milan,
        StPetersburg,
        HoChiMinhCity,
        Jakarta,
        HongKong,
        Manila,
        Shanghai,
        Taipei,
        Moscow,
        Sydney,
        Johannesburg,
        Kinshasa,
        Lagos,
        Khartoum,
        Santiago,
        NewYork,
        Essen,
        Osaka,
        Tokyo
    };
}